---
# handlers file for ansible-role-matrix-synapse

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart coturn
  service:
    name: coturn
    state: restarted

- name: restart matrix-synapse
  service:
    name: matrix-synapse
    state: restarted